//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ScanCompleteTasks struct {
	ID        int32 `sql:"primary_key"`
	CameraID  int32
	Kind      ScanKind
	Range     string
	Cursor    time.Time
	StartedAt time.Time
	Deleted   int32
	Upserted  int32
	Percent   float32
	Duration  int32
	Success   *bool
	Error     string
}
