// Code generated by generate-pubsub-events.sh; DO NOT EDIT.
package models

func (e EventDahuaDeviceCreated) EventTopic() string {
	return "EventDahuaDeviceCreated"
}

func (e EventDahuaDeviceUpdated) EventTopic() string {
	return "EventDahuaDeviceUpdated"
}

func (e EventDahuaDeviceDeleted) EventTopic() string {
	return "EventDahuaDeviceDeleted"
}

func (e EventDahuaEvent) EventTopic() string {
	return "EventDahuaEvent"
}

func (e EventDahuaEventWorkerConnecting) EventTopic() string {
	return "EventDahuaEventWorkerConnecting"
}

func (e EventDahuaEventWorkerConnect) EventTopic() string {
	return "EventDahuaEventWorkerConnect"
}

func (e EventDahuaEventWorkerDisconnect) EventTopic() string {
	return "EventDahuaEventWorkerDisconnect"
}

func (e EventDahuaCoaxialStatus) EventTopic() string {
	return "EventDahuaCoaxialStatus"
}

func (e EventDahuaQuickScanQueue) EventTopic() string {
	return "EventDahuaQuickScanQueue"
}

