// Code generated by generate-pubsub-events.sh; DO NOT EDIT.
package models

func (e EventDahuaCameraCreated) EventTopic() string {
	return "EventDahuaCameraCreated"
}

func (e EventDahuaCameraUpdated) EventTopic() string {
	return "EventDahuaCameraUpdated"
}

func (e EventDahuaCameraDeleted) EventTopic() string {
	return "EventDahuaCameraDeleted"
}

func (e EventDahuaCameraEvent) EventTopic() string {
	return "EventDahuaCameraEvent"
}

func (e EventDahuaEventWorkerConnecting) EventTopic() string {
	return "EventDahuaEventWorkerConnecting"
}

func (e EventDahuaEventWorkerConnect) EventTopic() string {
	return "EventDahuaEventWorkerConnect"
}

func (e EventDahuaEventWorkerDisconnect) EventTopic() string {
	return "EventDahuaEventWorkerDisconnect"
}

func (e EventDahuaCoaxialStatus) EventTopic() string {
	return "EventDahuaCoaxialStatus"
}

