// @generated by protobuf-ts 2.9.3 with parameter generate_dependencies
// @generated from protobuf file "rpc.proto" (syntax proto3)
// tslint:disable
import { Admin } from "./rpc";
import type { DeleteGroupReq } from "./rpc";
import type { Empty } from "./google/protobuf/empty";
import type { UpdateGroupReq } from "./rpc";
import type { CreateGroupResp } from "./rpc";
import type { CreateGroupReq } from "./rpc";
import type { GetGroupResp } from "./rpc";
import type { GetGroupReq } from "./rpc";
import type { ListGroupsResp } from "./rpc";
import type { ListGroupsReq } from "./rpc";
import { User } from "./rpc";
import type { ListMyGroupsResp } from "./rpc";
import type { ListMyGroupsReq } from "./rpc";
import type { RevokeAllMySessionsResp } from "./rpc";
import type { RevokeAllMySessionsReq } from "./rpc";
import type { RevokeMySessionResp } from "./rpc";
import type { RevokeMySessionReq } from "./rpc";
import type { UpdateMyPasswordResp } from "./rpc";
import type { UpdateMyPasswordReq } from "./rpc";
import type { UpdateMyUsernameResp } from "./rpc";
import type { UpdateMyUsernameReq } from "./rpc";
import { Page } from "./rpc";
import type { ProfileResp } from "./rpc";
import type { ProfileReq } from "./rpc";
import type { HomeResp } from "./rpc";
import type { HomeReq } from "./rpc";
import { Auth } from "./rpc";
import type { ForgotPasswordResp } from "./rpc";
import type { ForgotPasswordReq } from "./rpc";
import type { SignUpResp } from "./rpc";
import type { SignUpReq } from "./rpc";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { HelloWorld } from "./rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HelloResp } from "./rpc";
import type { HelloReq } from "./rpc";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
// ---------- HelloWorld

/**
 * @generated from protobuf service HelloWorld
 */
export interface IHelloWorldClient {
    /**
     * @generated from protobuf rpc: Hello(HelloReq) returns (HelloResp);
     */
    hello(input: HelloReq, options?: RpcOptions): UnaryCall<HelloReq, HelloResp>;
}
// ---------- HelloWorld

/**
 * @generated from protobuf service HelloWorld
 */
export class HelloWorldClient implements IHelloWorldClient, ServiceInfo {
    typeName = HelloWorld.typeName;
    methods = HelloWorld.methods;
    options = HelloWorld.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Hello(HelloReq) returns (HelloResp);
     */
    hello(input: HelloReq, options?: RpcOptions): UnaryCall<HelloReq, HelloResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HelloReq, HelloResp>("unary", this._transport, method, opt, input);
    }
}
// ---------- Auth

/**
 * @generated from protobuf service Auth
 */
export interface IAuthClient {
    /**
     * @generated from protobuf rpc: SignUp(SignUpReq) returns (SignUpResp);
     */
    signUp(input: SignUpReq, options?: RpcOptions): UnaryCall<SignUpReq, SignUpResp>;
    /**
     * @generated from protobuf rpc: ForgotPassword(ForgotPasswordReq) returns (ForgotPasswordResp);
     */
    forgotPassword(input: ForgotPasswordReq, options?: RpcOptions): UnaryCall<ForgotPasswordReq, ForgotPasswordResp>;
}
// ---------- Auth

/**
 * @generated from protobuf service Auth
 */
export class AuthClient implements IAuthClient, ServiceInfo {
    typeName = Auth.typeName;
    methods = Auth.methods;
    options = Auth.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SignUp(SignUpReq) returns (SignUpResp);
     */
    signUp(input: SignUpReq, options?: RpcOptions): UnaryCall<SignUpReq, SignUpResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignUpReq, SignUpResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ForgotPassword(ForgotPasswordReq) returns (ForgotPasswordResp);
     */
    forgotPassword(input: ForgotPasswordReq, options?: RpcOptions): UnaryCall<ForgotPasswordReq, ForgotPasswordResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ForgotPasswordReq, ForgotPasswordResp>("unary", this._transport, method, opt, input);
    }
}
// ---------- Page

/**
 * @generated from protobuf service Page
 */
export interface IPageClient {
    /**
     * @generated from protobuf rpc: Home(HomeReq) returns (HomeResp);
     */
    home(input: HomeReq, options?: RpcOptions): UnaryCall<HomeReq, HomeResp>;
    /**
     * @generated from protobuf rpc: Profile(ProfileReq) returns (ProfileResp);
     */
    profile(input: ProfileReq, options?: RpcOptions): UnaryCall<ProfileReq, ProfileResp>;
}
// ---------- Page

/**
 * @generated from protobuf service Page
 */
export class PageClient implements IPageClient, ServiceInfo {
    typeName = Page.typeName;
    methods = Page.methods;
    options = Page.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Home(HomeReq) returns (HomeResp);
     */
    home(input: HomeReq, options?: RpcOptions): UnaryCall<HomeReq, HomeResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HomeReq, HomeResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Profile(ProfileReq) returns (ProfileResp);
     */
    profile(input: ProfileReq, options?: RpcOptions): UnaryCall<ProfileReq, ProfileResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProfileReq, ProfileResp>("unary", this._transport, method, opt, input);
    }
}
// ---------- User

/**
 * @generated from protobuf service User
 */
export interface IUserClient {
    /**
     * @generated from protobuf rpc: UpdateMyUsername(UpdateMyUsernameReq) returns (UpdateMyUsernameResp);
     */
    updateMyUsername(input: UpdateMyUsernameReq, options?: RpcOptions): UnaryCall<UpdateMyUsernameReq, UpdateMyUsernameResp>;
    /**
     * @generated from protobuf rpc: UpdateMyPassword(UpdateMyPasswordReq) returns (UpdateMyPasswordResp);
     */
    updateMyPassword(input: UpdateMyPasswordReq, options?: RpcOptions): UnaryCall<UpdateMyPasswordReq, UpdateMyPasswordResp>;
    /**
     * @generated from protobuf rpc: RevokeMySession(RevokeMySessionReq) returns (RevokeMySessionResp);
     */
    revokeMySession(input: RevokeMySessionReq, options?: RpcOptions): UnaryCall<RevokeMySessionReq, RevokeMySessionResp>;
    /**
     * @generated from protobuf rpc: RevokeAllMySessions(RevokeAllMySessionsReq) returns (RevokeAllMySessionsResp);
     */
    revokeAllMySessions(input: RevokeAllMySessionsReq, options?: RpcOptions): UnaryCall<RevokeAllMySessionsReq, RevokeAllMySessionsResp>;
    /**
     * @generated from protobuf rpc: ListMyGroups(ListMyGroupsReq) returns (ListMyGroupsResp);
     */
    listMyGroups(input: ListMyGroupsReq, options?: RpcOptions): UnaryCall<ListMyGroupsReq, ListMyGroupsResp>;
}
// ---------- User

/**
 * @generated from protobuf service User
 */
export class UserClient implements IUserClient, ServiceInfo {
    typeName = User.typeName;
    methods = User.methods;
    options = User.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: UpdateMyUsername(UpdateMyUsernameReq) returns (UpdateMyUsernameResp);
     */
    updateMyUsername(input: UpdateMyUsernameReq, options?: RpcOptions): UnaryCall<UpdateMyUsernameReq, UpdateMyUsernameResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateMyUsernameReq, UpdateMyUsernameResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateMyPassword(UpdateMyPasswordReq) returns (UpdateMyPasswordResp);
     */
    updateMyPassword(input: UpdateMyPasswordReq, options?: RpcOptions): UnaryCall<UpdateMyPasswordReq, UpdateMyPasswordResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateMyPasswordReq, UpdateMyPasswordResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RevokeMySession(RevokeMySessionReq) returns (RevokeMySessionResp);
     */
    revokeMySession(input: RevokeMySessionReq, options?: RpcOptions): UnaryCall<RevokeMySessionReq, RevokeMySessionResp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevokeMySessionReq, RevokeMySessionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RevokeAllMySessions(RevokeAllMySessionsReq) returns (RevokeAllMySessionsResp);
     */
    revokeAllMySessions(input: RevokeAllMySessionsReq, options?: RpcOptions): UnaryCall<RevokeAllMySessionsReq, RevokeAllMySessionsResp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevokeAllMySessionsReq, RevokeAllMySessionsResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMyGroups(ListMyGroupsReq) returns (ListMyGroupsResp);
     */
    listMyGroups(input: ListMyGroupsReq, options?: RpcOptions): UnaryCall<ListMyGroupsReq, ListMyGroupsResp> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMyGroupsReq, ListMyGroupsResp>("unary", this._transport, method, opt, input);
    }
}
// ---------- Admin

/**
 * @generated from protobuf service Admin
 */
export interface IAdminClient {
    /**
     * @generated from protobuf rpc: ListGroups(ListGroupsReq) returns (ListGroupsResp);
     */
    listGroups(input: ListGroupsReq, options?: RpcOptions): UnaryCall<ListGroupsReq, ListGroupsResp>;
    /**
     * @generated from protobuf rpc: GetGroup(GetGroupReq) returns (GetGroupResp);
     */
    getGroup(input: GetGroupReq, options?: RpcOptions): UnaryCall<GetGroupReq, GetGroupResp>;
    /**
     * @generated from protobuf rpc: CreateGroup(CreateGroupReq) returns (CreateGroupResp);
     */
    createGroup(input: CreateGroupReq, options?: RpcOptions): UnaryCall<CreateGroupReq, CreateGroupResp>;
    /**
     * @generated from protobuf rpc: UpdateGroup(UpdateGroupReq) returns (google.protobuf.Empty);
     */
    updateGroup(input: UpdateGroupReq, options?: RpcOptions): UnaryCall<UpdateGroupReq, Empty>;
    /**
     * @generated from protobuf rpc: DeleteGroup(DeleteGroupReq) returns (google.protobuf.Empty);
     */
    deleteGroup(input: DeleteGroupReq, options?: RpcOptions): UnaryCall<DeleteGroupReq, Empty>;
}
// ---------- Admin

/**
 * @generated from protobuf service Admin
 */
export class AdminClient implements IAdminClient, ServiceInfo {
    typeName = Admin.typeName;
    methods = Admin.methods;
    options = Admin.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListGroups(ListGroupsReq) returns (ListGroupsResp);
     */
    listGroups(input: ListGroupsReq, options?: RpcOptions): UnaryCall<ListGroupsReq, ListGroupsResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListGroupsReq, ListGroupsResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetGroup(GetGroupReq) returns (GetGroupResp);
     */
    getGroup(input: GetGroupReq, options?: RpcOptions): UnaryCall<GetGroupReq, GetGroupResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetGroupReq, GetGroupResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateGroup(CreateGroupReq) returns (CreateGroupResp);
     */
    createGroup(input: CreateGroupReq, options?: RpcOptions): UnaryCall<CreateGroupReq, CreateGroupResp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateGroupReq, CreateGroupResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateGroup(UpdateGroupReq) returns (google.protobuf.Empty);
     */
    updateGroup(input: UpdateGroupReq, options?: RpcOptions): UnaryCall<UpdateGroupReq, Empty> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateGroupReq, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteGroup(DeleteGroupReq) returns (google.protobuf.Empty);
     */
    deleteGroup(input: DeleteGroupReq, options?: RpcOptions): UnaryCall<DeleteGroupReq, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteGroupReq, Empty>("unary", this._transport, method, opt, input);
    }
}
