// @generated by protobuf-ts 2.9.3 with parameter generate_dependencies
// @generated from protobuf file "rpc.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message Session
 */
export interface Session {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: string user_agent = 2;
     */
    userAgent: string;
    /**
     * @generated from protobuf field: string ip = 3;
     */
    ip: string;
    /**
     * @generated from protobuf field: string last_ip = 4;
     */
    lastIp: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp last_used_at_time = 5;
     */
    lastUsedAtTime?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at_time = 6;
     */
    createdAtTime?: Timestamp;
    /**
     * @generated from protobuf field: bool active = 7;
     */
    active: boolean;
    /**
     * @generated from protobuf field: bool current = 8;
     */
    current: boolean;
}
/**
 * @generated from protobuf message Group
 */
export interface Group {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp joined_at_time = 4;
     */
    joinedAtTime?: Timestamp;
}
/**
 * @generated from protobuf message HelloReq
 */
export interface HelloReq {
    /**
     * @generated from protobuf field: string subject = 1;
     */
    subject: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp current_time = 2;
     */
    currentTime?: Timestamp;
}
/**
 * @generated from protobuf message HelloResp
 */
export interface HelloResp {
    /**
     * @generated from protobuf field: string text = 1;
     */
    text: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp current_time = 2;
     */
    currentTime?: Timestamp;
}
/**
 * @generated from protobuf message SignUpReq
 */
export interface SignUpReq {
    /**
     * @generated from protobuf field: string email = 1;
     */
    email: string;
    /**
     * @generated from protobuf field: string username = 2;
     */
    username: string;
    /**
     * @generated from protobuf field: string password = 3;
     */
    password: string;
}
/**
 * @generated from protobuf message SignUpResp
 */
export interface SignUpResp {
}
/**
 * @generated from protobuf message ForgotPasswordReq
 */
export interface ForgotPasswordReq {
    /**
     * @generated from protobuf field: string email = 1;
     */
    email: string;
}
/**
 * @generated from protobuf message ForgotPasswordResp
 */
export interface ForgotPasswordResp {
}
/**
 * @generated from protobuf message PageHomeReq
 */
export interface PageHomeReq {
}
/**
 * @generated from protobuf message PageHomeResp
 */
export interface PageHomeResp {
    /**
     * @generated from protobuf field: int64 device_count = 1;
     */
    deviceCount: bigint;
}
/**
 * @generated from protobuf message PageProfileReq
 */
export interface PageProfileReq {
}
/**
 * @generated from protobuf message PageProfileResp
 */
export interface PageProfileResp {
    /**
     * @generated from protobuf field: string username = 1;
     */
    username: string;
    /**
     * @generated from protobuf field: string email = 2;
     */
    email: string;
    /**
     * @generated from protobuf field: bool admin = 3;
     */
    admin: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at_time = 4;
     */
    createdAtTime?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at_time = 5;
     */
    updatedAtTime?: Timestamp;
    /**
     * @generated from protobuf field: repeated Session sessions = 6;
     */
    sessions: Session[];
}
/**
 * @generated from protobuf message UpdateUsernameReq
 */
export interface UpdateUsernameReq {
    /**
     * @generated from protobuf field: string new_username = 1;
     */
    newUsername: string;
}
/**
 * @generated from protobuf message UpdateUsernameResp
 */
export interface UpdateUsernameResp {
}
/**
 * @generated from protobuf message UpdatePasswordReq
 */
export interface UpdatePasswordReq {
    /**
     * @generated from protobuf field: string old_password = 1;
     */
    oldPassword: string;
    /**
     * @generated from protobuf field: string new_password = 2;
     */
    newPassword: string;
}
/**
 * @generated from protobuf message UpdatePasswordResp
 */
export interface UpdatePasswordResp {
}
/**
 * @generated from protobuf message RevokeSessionReq
 */
export interface RevokeSessionReq {
    /**
     * @generated from protobuf field: int64 session_id = 1;
     */
    sessionId: bigint;
}
/**
 * @generated from protobuf message RevokeSessionResp
 */
export interface RevokeSessionResp {
}
/**
 * @generated from protobuf message RevokeAllSessionsReq
 */
export interface RevokeAllSessionsReq {
}
/**
 * @generated from protobuf message RevokeAllSessionsResp
 */
export interface RevokeAllSessionsResp {
}
/**
 * @generated from protobuf message ListMyGroupsReq
 */
export interface ListMyGroupsReq {
}
/**
 * @generated from protobuf message ListMyGroupsResp
 */
export interface ListMyGroupsResp {
    /**
     * @generated from protobuf field: repeated Group groups = 1;
     */
    groups: Group[];
}
/**
 * @generated from protobuf message ListGroupsReq
 */
export interface ListGroupsReq {
    /**
     * @generated from protobuf field: int32 page = 1;
     */
    page: number;
    /**
     * @generated from protobuf field: int32 per_page = 2;
     */
    perPage: number;
}
/**
 * @generated from protobuf message ListGroupsResp
 */
export interface ListGroupsResp {
    /**
     * @generated from protobuf field: repeated Group groups = 1;
     */
    groups: Group[];
    /**
     * @generated from protobuf field: int32 page = 2;
     */
    page: number;
    /**
     * @generated from protobuf field: int32 per_page = 3;
     */
    perPage: number;
    /**
     * @generated from protobuf field: int64 total_pages = 4;
     */
    totalPages: bigint;
    /**
     * @generated from protobuf field: int64 total_items = 5;
     */
    totalItems: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class Session$Type extends MessageType<Session> {
    constructor() {
        super("Session", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "user_agent", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "ip", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "last_ip", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "last_used_at_time", kind: "message", T: () => Timestamp },
            { no: 6, name: "created_at_time", kind: "message", T: () => Timestamp },
            { no: 7, name: "active", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "current", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Session
 */
export const Session = new Session$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Group$Type extends MessageType<Group> {
    constructor() {
        super("Group", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "joined_at_time", kind: "message", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Group
 */
export const Group = new Group$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HelloReq$Type extends MessageType<HelloReq> {
    constructor() {
        super("HelloReq", [
            { no: 1, name: "subject", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "current_time", kind: "message", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message HelloReq
 */
export const HelloReq = new HelloReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HelloResp$Type extends MessageType<HelloResp> {
    constructor() {
        super("HelloResp", [
            { no: 1, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "current_time", kind: "message", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message HelloResp
 */
export const HelloResp = new HelloResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SignUpReq$Type extends MessageType<SignUpReq> {
    constructor() {
        super("SignUpReq", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message SignUpReq
 */
export const SignUpReq = new SignUpReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SignUpResp$Type extends MessageType<SignUpResp> {
    constructor() {
        super("SignUpResp", []);
    }
}
/**
 * @generated MessageType for protobuf message SignUpResp
 */
export const SignUpResp = new SignUpResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ForgotPasswordReq$Type extends MessageType<ForgotPasswordReq> {
    constructor() {
        super("ForgotPasswordReq", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ForgotPasswordReq
 */
export const ForgotPasswordReq = new ForgotPasswordReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ForgotPasswordResp$Type extends MessageType<ForgotPasswordResp> {
    constructor() {
        super("ForgotPasswordResp", []);
    }
}
/**
 * @generated MessageType for protobuf message ForgotPasswordResp
 */
export const ForgotPasswordResp = new ForgotPasswordResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageHomeReq$Type extends MessageType<PageHomeReq> {
    constructor() {
        super("PageHomeReq", []);
    }
}
/**
 * @generated MessageType for protobuf message PageHomeReq
 */
export const PageHomeReq = new PageHomeReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageHomeResp$Type extends MessageType<PageHomeResp> {
    constructor() {
        super("PageHomeResp", [
            { no: 1, name: "device_count", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message PageHomeResp
 */
export const PageHomeResp = new PageHomeResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageProfileReq$Type extends MessageType<PageProfileReq> {
    constructor() {
        super("PageProfileReq", []);
    }
}
/**
 * @generated MessageType for protobuf message PageProfileReq
 */
export const PageProfileReq = new PageProfileReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageProfileResp$Type extends MessageType<PageProfileResp> {
    constructor() {
        super("PageProfileResp", [
            { no: 1, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "admin", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "created_at_time", kind: "message", T: () => Timestamp },
            { no: 5, name: "updated_at_time", kind: "message", T: () => Timestamp },
            { no: 6, name: "sessions", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Session }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message PageProfileResp
 */
export const PageProfileResp = new PageProfileResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateUsernameReq$Type extends MessageType<UpdateUsernameReq> {
    constructor() {
        super("UpdateUsernameReq", [
            { no: 1, name: "new_username", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message UpdateUsernameReq
 */
export const UpdateUsernameReq = new UpdateUsernameReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateUsernameResp$Type extends MessageType<UpdateUsernameResp> {
    constructor() {
        super("UpdateUsernameResp", []);
    }
}
/**
 * @generated MessageType for protobuf message UpdateUsernameResp
 */
export const UpdateUsernameResp = new UpdateUsernameResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePasswordReq$Type extends MessageType<UpdatePasswordReq> {
    constructor() {
        super("UpdatePasswordReq", [
            { no: 1, name: "old_password", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "new_password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message UpdatePasswordReq
 */
export const UpdatePasswordReq = new UpdatePasswordReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePasswordResp$Type extends MessageType<UpdatePasswordResp> {
    constructor() {
        super("UpdatePasswordResp", []);
    }
}
/**
 * @generated MessageType for protobuf message UpdatePasswordResp
 */
export const UpdatePasswordResp = new UpdatePasswordResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RevokeSessionReq$Type extends MessageType<RevokeSessionReq> {
    constructor() {
        super("RevokeSessionReq", [
            { no: 1, name: "session_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message RevokeSessionReq
 */
export const RevokeSessionReq = new RevokeSessionReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RevokeSessionResp$Type extends MessageType<RevokeSessionResp> {
    constructor() {
        super("RevokeSessionResp", []);
    }
}
/**
 * @generated MessageType for protobuf message RevokeSessionResp
 */
export const RevokeSessionResp = new RevokeSessionResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RevokeAllSessionsReq$Type extends MessageType<RevokeAllSessionsReq> {
    constructor() {
        super("RevokeAllSessionsReq", []);
    }
}
/**
 * @generated MessageType for protobuf message RevokeAllSessionsReq
 */
export const RevokeAllSessionsReq = new RevokeAllSessionsReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RevokeAllSessionsResp$Type extends MessageType<RevokeAllSessionsResp> {
    constructor() {
        super("RevokeAllSessionsResp", []);
    }
}
/**
 * @generated MessageType for protobuf message RevokeAllSessionsResp
 */
export const RevokeAllSessionsResp = new RevokeAllSessionsResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListMyGroupsReq$Type extends MessageType<ListMyGroupsReq> {
    constructor() {
        super("ListMyGroupsReq", []);
    }
}
/**
 * @generated MessageType for protobuf message ListMyGroupsReq
 */
export const ListMyGroupsReq = new ListMyGroupsReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListMyGroupsResp$Type extends MessageType<ListMyGroupsResp> {
    constructor() {
        super("ListMyGroupsResp", [
            { no: 1, name: "groups", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Group }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ListMyGroupsResp
 */
export const ListMyGroupsResp = new ListMyGroupsResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListGroupsReq$Type extends MessageType<ListGroupsReq> {
    constructor() {
        super("ListGroupsReq", [
            { no: 1, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "per_page", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ListGroupsReq
 */
export const ListGroupsReq = new ListGroupsReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListGroupsResp$Type extends MessageType<ListGroupsResp> {
    constructor() {
        super("ListGroupsResp", [
            { no: 1, name: "groups", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Group },
            { no: 2, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "per_page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "total_pages", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "total_items", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ListGroupsResp
 */
export const ListGroupsResp = new ListGroupsResp$Type();
/**
 * @generated ServiceType for protobuf service HelloWorld
 */
export const HelloWorld = new ServiceType("HelloWorld", [
    { name: "Hello", options: {}, I: HelloReq, O: HelloResp }
]);
/**
 * @generated ServiceType for protobuf service Auth
 */
export const Auth = new ServiceType("Auth", [
    { name: "SignUp", options: {}, I: SignUpReq, O: SignUpResp },
    { name: "ForgotPassword", options: {}, I: ForgotPasswordReq, O: ForgotPasswordResp }
]);
/**
 * @generated ServiceType for protobuf service Page
 */
export const Page = new ServiceType("Page", [
    { name: "Home", options: {}, I: PageHomeReq, O: PageHomeResp },
    { name: "Profile", options: {}, I: PageProfileReq, O: PageProfileResp }
]);
/**
 * @generated ServiceType for protobuf service User
 */
export const User = new ServiceType("User", [
    { name: "UpdateUsername", options: {}, I: UpdateUsernameReq, O: UpdateUsernameResp },
    { name: "UpdatePassword", options: {}, I: UpdatePasswordReq, O: UpdatePasswordResp },
    { name: "RevokeSession", options: {}, I: RevokeSessionReq, O: RevokeSessionResp },
    { name: "RevokeAllSessions", options: {}, I: RevokeAllSessionsReq, O: RevokeAllSessionsResp },
    { name: "ListMyGroups", options: {}, I: ListMyGroupsReq, O: ListMyGroupsResp }
]);
/**
 * @generated ServiceType for protobuf service Admin
 */
export const Admin = new ServiceType("Admin", [
    { name: "ListGroups", options: {}, I: ListGroupsReq, O: ListGroupsResp }
]);
