// Code generated by generate-pubsub-events.sh; DO NOT EDIT.
package event

func (e EventQueued) EventTopic() string {
	return "EventQueued"
}

func (e EventCreated) EventTopic() string {
	return "EventCreated"
}

func (e DahuaEvent) EventTopic() string {
	return "DahuaEvent"
}

func (e DahuaEventWorkerConnecting) EventTopic() string {
	return "DahuaEventWorkerConnecting"
}

func (e DahuaEventWorkerConnect) EventTopic() string {
	return "DahuaEventWorkerConnect"
}

func (e DahuaEventWorkerDisconnect) EventTopic() string {
	return "DahuaEventWorkerDisconnect"
}

func (e DahuaCoaxialStatus) EventTopic() string {
	return "DahuaCoaxialStatus"
}

