//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type UserSessions struct {
	UserID     int32
	Token      string
	ClientID   string
	IPAddress  string
	ExpiredAt  time.Time
	LastUsedAt time.Time
	IssuedAt   time.Time
}
