// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"time"

	"github.com/ItsNotGoodName/ipcmanview/internal/models"
)

type DahuaCamera struct {
	ID        int64
	Name      string
	Address   string
	Username  string
	Password  string
	Location  models.Location
	CreatedAt time.Time
}
